/**
 * List of words that indicates the first word of `description` and where the words for `name` ends.
 *
 * For example:
 *
 * string: "Jonny Age: 19"
 * divider word: "Age"
 *
 * Result: {name: "Jonny", description: "Age: 19"}
 */
export const nameDescDividerWords = [
  'amar',
  'adalah',
  'data',
  'desa',
  'berdasarkan',
  'bergabung',
  'berubah',
  'cakupan',
  'duplikasi',
  'duplikat',
  'DS',
  'DITJEN',
  'diperbaru',
  'EMEKARAN',
  'hasil',
  'kec',
  'kel',
  'kepbup',
  'keputusan',
  'klarifikasi',
  'koreksi',
  'lampiran',
  'letak',
  'menjadi',
  'nagari',
  'nama',
  'nd rekom',
  'PEMAKARAN',
  'pembentukan',
  'PEMEAKRAN',
  'PEMEBNTUKAN',
  'PEMEKAAN',
  'PEMEKRAN',
  'pemekaran',
  'PEMEKERAN',
  'PENGABUNGAN',
  'pengangkatan',
  'PENGKATAN',
  'penggabungan',
  'penghapusan',
  'PENGHPUSAN',
  'peningkatan',
  'penyampaian',
  'penyerahan',
  'peraturan',
  'perbaikan',
  'perbup',
  'perda',
  'perub',
  'perubahan',
  'pmd',
  'PMKRAN',
  'PMKRN',
  'penataan',
  'pindah',
  'PRBHAN',
  'PTSAN',
  'putusan',
  'qanun',
  'rancang',
  'rekomendasi',
  'sebelum',
  'sebelumnya',
  'semua',
  'SEMUAL',
  'SEMUILA',
  'SEMUKA',
  'semula',
  'SEMULAWIL',
  'sesuai',
  'sk',
  'SMLA',
  'SMULA',
  'srt',
  'SSEMULA',
  'surat',
  'tentang',
  'ttg',
  'undang',
  'uu',
  'wil',
  'wilayah',
];

export const forceDividerWords = [
  'PMD',
];
